/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyResponse {
    #[serde(rename = "result")]
    pub result: Option<serde_json::Value>,
    #[serde(rename = "msg")]
    pub msg: Option<serde_json::Value>,
    /// The API key that can be used to authenticate as the requested user. 
    #[serde(rename = "api_key")]
    pub api_key: String,
    /// The email address of the user who owns the API key 
    #[serde(rename = "email")]
    pub email: String,
}

impl ApiKeyResponse {
    pub fn new(result: Option<serde_json::Value>, msg: Option<serde_json::Value>, api_key: String, email: String) -> ApiKeyResponse {
        ApiKeyResponse {
            result,
            msg,
            api_key,
            email,
        }
    }
}


