/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyResponseAllOf {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<serde_json::Value>,
    /// The API key that can be used to authenticate as the requested user. 
    #[serde(rename = "api_key")]
    pub api_key: String,
    /// The email address of the user who owns the API key 
    #[serde(rename = "email")]
    pub email: String,
}

impl ApiKeyResponseAllOf {
    pub fn new(api_key: String, email: String) -> ApiKeyResponseAllOf {
        ApiKeyResponseAllOf {
            result: None,
            msg: None,
            api_key,
            email,
        }
    }
}


