/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadEventQueueIdError {
    #[serde(rename = "result")]
    pub result: Option<serde_json::Value>,
    #[serde(rename = "msg")]
    pub msg: Option<serde_json::Value>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<serde_json::Value>,
    /// The string that identifies the invalid event queue. 
    #[serde(rename = "queue_id", skip_serializing_if = "Option::is_none")]
    pub queue_id: Option<String>,
}

impl BadEventQueueIdError {
    pub fn new(result: Option<serde_json::Value>, msg: Option<serde_json::Value>) -> BadEventQueueIdError {
        BadEventQueueIdError {
            result,
            msg,
            code: None,
            queue_id: None,
        }
    }
}


