/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BasicStream {
    #[serde(rename = "stream_id", skip_serializing_if = "Option::is_none")]
    pub stream_id: Option<serde_json::Value>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<serde_json::Value>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<serde_json::Value>,
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<serde_json::Value>,
    #[serde(rename = "invite_only", skip_serializing_if = "Option::is_none")]
    pub invite_only: Option<serde_json::Value>,
    #[serde(rename = "rendered_description", skip_serializing_if = "Option::is_none")]
    pub rendered_description: Option<serde_json::Value>,
    #[serde(rename = "is_web_public", skip_serializing_if = "Option::is_none")]
    pub is_web_public: Option<serde_json::Value>,
    #[serde(rename = "stream_post_policy", skip_serializing_if = "Option::is_none")]
    pub stream_post_policy: Option<serde_json::Value>,
    #[serde(rename = "message_retention_days", skip_serializing_if = "Option::is_none")]
    pub message_retention_days: Option<serde_json::Value>,
    #[serde(rename = "history_public_to_subscribers", skip_serializing_if = "Option::is_none")]
    pub history_public_to_subscribers: Option<serde_json::Value>,
    #[serde(rename = "first_message_id", skip_serializing_if = "Option::is_none")]
    pub first_message_id: Option<serde_json::Value>,
    #[serde(rename = "is_announcement_only", skip_serializing_if = "Option::is_none")]
    pub is_announcement_only: Option<serde_json::Value>,
}

impl BasicStream {
    pub fn new() -> BasicStream {
        BasicStream {
            stream_id: None,
            name: None,
            description: None,
            date_created: None,
            invite_only: None,
            rendered_description: None,
            is_web_public: None,
            stream_post_policy: None,
            message_retention_days: None,
            history_public_to_subscribers: None,
            first_message_id: None,
            is_announcement_only: None,
        }
    }
}


