/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodedErrorBase {
    #[serde(rename = "result")]
    pub result: Option<serde_json::Value>,
    #[serde(rename = "msg")]
    pub msg: Option<serde_json::Value>,
    /// A string that identifies the error. 
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl CodedErrorBase {
    pub fn new(result: Option<serde_json::Value>, msg: Option<serde_json::Value>) -> CodedErrorBase {
        CodedErrorBase {
            result,
            msg,
            code: None,
        }
    }
}


