/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CustomProfileField : Dictionary containing the details of a custom profile field configured for this organization. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomProfileField {
    /// The ID of the custom profile field.  This will be referenced in custom the profile fields section of user objects. 
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// An integer indicating the type of the custom profile field, which determines how it is configured and displayed to users.  See the [Add custom profile fields](/help/add-custom-profile-fields) article for details on what each type means.  * **1**: Short text * **2**: Long text * **3**: List of options * **4**: Date picker * **5**: Link * **6**: Person picker * **7**: External account 
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<i32>,
    /// Custom profile fields are displayed in both settings UI and UI showing users' profiles in increasing `order`. 
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    /// The name of the custom profile field. 
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The help text to be displayed for the custom profile field in user-facing settings UI for configuring custom profile fields. 
    #[serde(rename = "hint", skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,
    /// Field types 3 (List of options) and 7 (External account) support storing additional configuration for the field type in the `field_data` attribute.  For field type 3 (List of options), this attribute is a JSON dictionary defining the choices and the order they will be displayed in the dropdown UI for individual users to select an option.  The interface for field type 7 is not yet stabilized. 
    #[serde(rename = "field_data", skip_serializing_if = "Option::is_none")]
    pub field_data: Option<String>,
}

impl CustomProfileField {
    /// Dictionary containing the details of a custom profile field configured for this organization. 
    pub fn new() -> CustomProfileField {
        CustomProfileField {
            id: None,
            _type: None,
            order: None,
            name: None,
            hint: None,
            field_data: None,
        }
    }
}


