/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DefaultStreamGroup : Dictionary containing details of a default stream group. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultStreamGroup {
    /// Name of the default stream group. 
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description of the default stream group. 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// id of the default stream group. 
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Array containing details about the streams in the default stream group. 
    #[serde(rename = "streams", skip_serializing_if = "Option::is_none")]
    pub streams: Option<Vec<crate::models::BasicStream>>,
}

impl DefaultStreamGroup {
    /// Dictionary containing details of a default stream group. 
    pub fn new() -> DefaultStreamGroup {
        DefaultStreamGroup {
            name: None,
            description: None,
            id: None,
            streams: None,
        }
    }
}


