/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmojiReaction {
    #[serde(rename = "emoji_code", skip_serializing_if = "Option::is_none")]
    pub emoji_code: Option<serde_json::Value>,
    #[serde(rename = "emoji_name", skip_serializing_if = "Option::is_none")]
    pub emoji_name: Option<serde_json::Value>,
    #[serde(rename = "reaction_type", skip_serializing_if = "Option::is_none")]
    pub reaction_type: Option<serde_json::Value>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<serde_json::Value>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<serde_json::Value>,
}

impl EmojiReaction {
    pub fn new() -> EmojiReaction {
        EmojiReaction {
            emoji_code: None,
            emoji_name: None,
            reaction_type: None,
            user_id: None,
            user: None,
        }
    }
}


