/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonSuccessBase {
    #[serde(rename = "result")]
    pub result: Result,
    #[serde(rename = "msg")]
    pub msg: String,
}

impl JsonSuccessBase {
    pub fn new(result: Result, msg: String) -> JsonSuccessBase {
        JsonSuccessBase {
            result,
            msg,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "success")]
    Success,
}

