/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagesAllOf {
    #[serde(rename = "avatar_url", skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<serde_json::Value>,
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<serde_json::Value>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<serde_json::Value>,
    #[serde(rename = "content_type", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<serde_json::Value>,
    #[serde(rename = "display_recipient", skip_serializing_if = "Option::is_none")]
    pub display_recipient: Option<serde_json::Value>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<serde_json::Value>,
    #[serde(rename = "is_me_message", skip_serializing_if = "Option::is_none")]
    pub is_me_message: Option<serde_json::Value>,
    #[serde(rename = "reactions", skip_serializing_if = "Option::is_none")]
    pub reactions: Option<serde_json::Value>,
    #[serde(rename = "recipient_id", skip_serializing_if = "Option::is_none")]
    pub recipient_id: Option<serde_json::Value>,
    #[serde(rename = "sender_email", skip_serializing_if = "Option::is_none")]
    pub sender_email: Option<serde_json::Value>,
    #[serde(rename = "sender_full_name", skip_serializing_if = "Option::is_none")]
    pub sender_full_name: Option<serde_json::Value>,
    #[serde(rename = "sender_id", skip_serializing_if = "Option::is_none")]
    pub sender_id: Option<serde_json::Value>,
    #[serde(rename = "sender_realm_str", skip_serializing_if = "Option::is_none")]
    pub sender_realm_str: Option<serde_json::Value>,
    #[serde(rename = "stream_id", skip_serializing_if = "Option::is_none")]
    pub stream_id: Option<serde_json::Value>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<serde_json::Value>,
    #[serde(rename = "topic_links", skip_serializing_if = "Option::is_none")]
    pub topic_links: Option<serde_json::Value>,
    #[serde(rename = "submessages", skip_serializing_if = "Option::is_none")]
    pub submessages: Option<serde_json::Value>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<serde_json::Value>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<serde_json::Value>,
}

impl MessagesAllOf {
    pub fn new() -> MessagesAllOf {
        MessagesAllOf {
            avatar_url: None,
            client: None,
            content: None,
            content_type: None,
            display_recipient: None,
            id: None,
            is_me_message: None,
            reactions: None,
            recipient_id: None,
            sender_email: None,
            sender_full_name: None,
            sender_id: None,
            sender_realm_str: None,
            stream_id: None,
            subject: None,
            topic_links: None,
            submessages: None,
            timestamp: None,
            _type: None,
        }
    }
}


