/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NonExistingStreamError {
    #[serde(rename = "result")]
    pub result: Option<serde_json::Value>,
    #[serde(rename = "msg")]
    pub msg: Option<serde_json::Value>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<serde_json::Value>,
    /// The name of the stream that could not be found. 
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<String>,
}

impl NonExistingStreamError {
    pub fn new(result: Option<serde_json::Value>, msg: Option<serde_json::Value>) -> NonExistingStreamError {
        NonExistingStreamError {
            result,
            msg,
            code: None,
            stream: None,
        }
    }
}


