/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RealmDomain : Object containing details of the newly added domain. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealmDomain {
    /// The new allowed domain. 
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Whether subdomains are allowed for this domain. 
    #[serde(rename = "allow_subdomains", skip_serializing_if = "Option::is_none")]
    pub allow_subdomains: Option<bool>,
}

impl RealmDomain {
    /// Object containing details of the newly added domain. 
    pub fn new() -> RealmDomain {
        RealmDomain {
            domain: None,
            allow_subdomains: None,
        }
    }
}


