/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subscriptions {
    /// The unique ID of a stream. 
    #[serde(rename = "stream_id", skip_serializing_if = "Option::is_none")]
    pub stream_id: Option<i32>,
    /// The name of a stream. 
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The short description of a stream in text/markdown format, intended to be used to prepopulate UI for editing a stream's description. 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A short description of a stream rendered as HTML, intended to be used when displaying the stream description in a UI.  One should use the standard Zulip rendered_markdown CSS when displaying this content so that emoji, LaTeX, and other syntax work correctly.  And any client-side security logic for user-generated message content should be applied when displaying this HTML as though it were the body of a Zulip message. 
    #[serde(rename = "rendered_description", skip_serializing_if = "Option::is_none")]
    pub rendered_description: Option<String>,
    /// The UNIX timestamp for when the stream was created, in UTC seconds.  **Changes**: New in Zulip 4.0 (feature level 30). 
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<i32>,
    /// Specifies whether the stream is private or not. Only people who have been invited can access a private stream. 
    #[serde(rename = "invite_only", skip_serializing_if = "Option::is_none")]
    pub invite_only: Option<bool>,
    /// A list of user IDs of users who are also subscribed to a given stream. Included only if `include_subscribers` is `true`. 
    #[serde(rename = "subscribers", skip_serializing_if = "Option::is_none")]
    pub subscribers: Option<Vec<i32>>,
    /// A boolean specifying whether desktop notifications are enabled for the given stream.  A null value means the value of this setting should be inherited from the user-level default setting, enable_stream_desktop_notifications, for this stream. 
    #[serde(rename = "desktop_notifications", skip_serializing_if = "Option::is_none")]
    pub desktop_notifications: Option<bool>,
    /// A boolean specifying whether email notifications are enabled for the given stream.  A null value means the value of this setting should be inherited from the user-level default setting, enable_stream_email_notifications, for this stream. 
    #[serde(rename = "email_notifications", skip_serializing_if = "Option::is_none")]
    pub email_notifications: Option<bool>,
    /// A boolean specifying whether wildcard mentions trigger notifications as though they were personal mentions in this stream.  A null value means the value of this setting should be inherited from the user-level default setting, wildcard_mentions_notify, for this stream. 
    #[serde(rename = "wildcard_mentions_notify", skip_serializing_if = "Option::is_none")]
    pub wildcard_mentions_notify: Option<bool>,
    /// A boolean specifying whether push notifications are enabled for the given stream.  A null value means the value of this setting should be inherited from the user-level default setting, enable_stream_push_notifications, for this stream. 
    #[serde(rename = "push_notifications", skip_serializing_if = "Option::is_none")]
    pub push_notifications: Option<bool>,
    /// A boolean specifying whether audible notifications are enabled for the given stream.  A null value means the value of this setting should be inherited from the user-level default setting, enable_stream_audible_notifications, for this stream. 
    #[serde(rename = "audible_notifications", skip_serializing_if = "Option::is_none")]
    pub audible_notifications: Option<bool>,
    /// A boolean specifying whether the given stream has been pinned to the top. 
    #[serde(rename = "pin_to_top", skip_serializing_if = "Option::is_none")]
    pub pin_to_top: Option<bool>,
    /// Email address of the given stream, used for [sending emails to the stream](/help/message-a-stream-by-email). 
    #[serde(rename = "email_address", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    /// Whether the user has muted the stream. Muted streams do not count towards your total unread count and do not show up in `All messages` view (previously known as `Home` view).  **Changes**: Prior to Zulip 2.1, this feature was represented by the more confusingly named `in_home_view` (with the opposite value, `in_home_view=!is_muted`). 
    #[serde(rename = "is_muted", skip_serializing_if = "Option::is_none")]
    pub is_muted: Option<bool>,
    /// Legacy property for if the given stream is muted, with inverted meeting.  **Deprecated**; clients should use is_muted where available. 
    #[serde(rename = "in_home_view", skip_serializing_if = "Option::is_none")]
    pub in_home_view: Option<bool>,
    /// Whether only organization administrators can post to the stream.  **Changes**: Deprecated in Zulip 3.0 (feature level 1), use `stream_post_policy` instead. 
    #[serde(rename = "is_announcement_only", skip_serializing_if = "Option::is_none")]
    pub is_announcement_only: Option<bool>,
    /// Whether the stream has been configured to allow unauthenticated access to its message history from the web. 
    #[serde(rename = "is_web_public", skip_serializing_if = "Option::is_none")]
    pub is_web_public: Option<bool>,
    /// The user's role within the stream (distinct from the user's [organization-level role](/help/roles-and-permissions)). Valid values are:  * 20 => Stream administrator. * 50 => Subscriber.  **Changes**: New in Zulip 4.0 (feature level 31). 
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    /// The user's personal color for the stream. 
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Policy for which users can post messages to the stream.  * 1 => Any user can post. * 2 => Only administrators can post. * 3 => Only new members can post.  **Changes**: New in Zulip 3.0, replacing the previous `is_announcement_only` boolean. 
    #[serde(rename = "stream_post_policy", skip_serializing_if = "Option::is_none")]
    pub stream_post_policy: Option<i32>,
    /// Number of days that messages sent to this stream will be stored before being automatically deleted by the [message retention policy](/help/message-retention-policy).  There are two special values:  * `null`, the default, means the stream will inherit the organization   level setting. * `-1` encodes retaining messages in this stream forever.  **Changes**: New in Zulip 3.0 (feature level 17). 
    #[serde(rename = "message_retention_days", skip_serializing_if = "Option::is_none")]
    pub message_retention_days: Option<i32>,
    /// Whether the history of the stream is public to its subscribers.  Currently always true for public streams (i.e. invite_only=False implies history_public_to_subscribers=True), but clients should not make that assumption, as we may change that behavior in the future. 
    #[serde(rename = "history_public_to_subscribers", skip_serializing_if = "Option::is_none")]
    pub history_public_to_subscribers: Option<bool>,
    /// The id of the first message in the stream.  Intended to help clients determine whether they need to display UI like the \"more topics\" widget that would suggest the stream has older history that can be accessed.  Null is used for streams with no message history. 
    #[serde(rename = "first_message_id", skip_serializing_if = "Option::is_none")]
    pub first_message_id: Option<i32>,
    /// The average number of messages sent to the stream in recent weeks, rounded to the nearest integer.  Null means the stream was recently created and there is insufficient data to estimate the average traffic. 
    #[serde(rename = "stream_weekly_traffic", skip_serializing_if = "Option::is_none")]
    pub stream_weekly_traffic: Option<i32>,
}

impl Subscriptions {
    pub fn new() -> Subscriptions {
        Subscriptions {
            stream_id: None,
            name: None,
            description: None,
            rendered_description: None,
            date_created: None,
            invite_only: None,
            subscribers: None,
            desktop_notifications: None,
            email_notifications: None,
            wildcard_mentions_notify: None,
            push_notifications: None,
            audible_notifications: None,
            pin_to_top: None,
            email_address: None,
            is_muted: None,
            in_home_view: None,
            is_announcement_only: None,
            is_web_public: None,
            role: None,
            color: None,
            stream_post_policy: None,
            message_retention_days: None,
            history_public_to_subscribers: None,
            first_message_id: None,
            stream_weekly_traffic: None,
        }
    }
}

/// The user's role within the stream (distinct from the user's [organization-level role](/help/roles-and-permissions)). Valid values are:  * 20 => Stream administrator. * 50 => Subscriber.  **Changes**: New in Zulip 4.0 (feature level 31). 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "20")]
    _20,
    #[serde(rename = "50")]
    _50,
}

